import { DictationLesson } from "@/types/dictation";

export const mockDictationLesson: DictationLesson = {
  id: "dictation-001",
  title: "Basic Greetings",
  description: "Learn how to write basic Vietnamese greetings",
  totalQuestions: 7,
  currentQuestionIndex: 0,
  lives: 5,
  maxLives: 5,
  progress: 0,
  isCompleted: false,
  score: 0,
  questions: [
    {
      id: "q1",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Chào!",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w1", text: "passport" },
        { id: "w2", text: "yes" },
        { id: "w3", text: "Hi" },
        { id: "w4", text: "Hello" },
        { id: "w5", text: "I" },
      ],
      correctAnswers: [
        ["w3"], // Hi
        ["w4"], // Hello
      ],
      explanation: "Chào! means 'Hi' or 'Hello' in Vietnamese",
      audioUrl: "/audio/chao.mp3",
    },
    {
      id: "q2",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Tạm biệt",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w6", text: "Goodbye" },
        { id: "w7", text: "Thank you" },
        { id: "w8", text: "Please" },
        { id: "w9", text: "Sorry" },
        { id: "w10", text: "Excuse me" },
      ],
      correctAnswers: [["w6"]],
      explanation: "Tạm biệt means 'Goodbye' in Vietnamese",
      audioUrl: "/audio/tam-biet.mp3",
    },
    {
      id: "q3",
      type: "review_word",
      instruction: "Write this in Vietnamese",
      targetWord: "Thank you",
      targetLanguage: "en",
      answerLanguage: "vi",
      wordOptions: [
        { id: "w11", text: "Xin chào" },
        { id: "w12", text: "Cảm ơn" },
        { id: "w13", text: "Xin lỗi" },
        { id: "w14", text: "Làm ơn" },
        { id: "w15", text: "Tạm biệt" },
      ],
      correctAnswers: [["w12"]],
      explanation: "Thank you is 'Cảm ơn' in Vietnamese",
      audioUrl: "/audio/cam-on.mp3",
    },
    {
      id: "q4",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Xin lỗi",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w16", text: "Sorry" },
        { id: "w17", text: "Please" },
        { id: "w18", text: "Thank you" },
        { id: "w19", text: "Hello" },
        { id: "w20", text: "Goodbye" },
      ],
      correctAnswers: [["w16"]],
      explanation: "Xin lỗi means 'Sorry' in Vietnamese",
      audioUrl: "/audio/xin-loi.mp3",
    },
    {
      id: "q5",
      type: "review_word",
      instruction: "Write this in Vietnamese",
      targetWord: "Please",
      targetLanguage: "en",
      answerLanguage: "vi",
      wordOptions: [
        { id: "w21", text: "Làm ơn" },
        { id: "w22", text: "Xin lỗi" },
        { id: "w23", text: "Cảm ơn" },
        { id: "w24", text: "Xin chào" },
        { id: "w25", text: "Tạm biệt" },
      ],
      correctAnswers: [["w21"]],
      explanation: "Please is 'Làm ơn' in Vietnamese",
      audioUrl: "/audio/lam-on.mp3",
    },
    {
      id: "q6",
      type: "new_word",
      instruction: "Write this sentence in English",
      targetWord: "Tôi tên là Nam",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w26", text: "My" },
        { id: "w27", text: "name" },
        { id: "w28", text: "is" },
        { id: "w29", text: "Nam" },
        { id: "w30", text: "I" },
        { id: "w31", text: "am" },
        { id: "w32", text: "called" },
        { id: "w33", text: "John" },
      ],
      correctAnswers: [
        ["w26", "w27", "w28", "w29"], // My name is Nam
        ["w30", "w31", "w29"], // I am Nam
      ],
      explanation:
        "Tôi tên là Nam means 'My name is Nam' or 'I am Nam' in English",
      audioUrl: "/audio/toi-ten-la-nam.mp3",
    },
    {
      id: "q7",
      type: "review_word",
      instruction: "Write this sentence in Vietnamese",
      targetWord: "How are you today?",
      targetLanguage: "en",
      answerLanguage: "vi",
      wordOptions: [
        { id: "w34", text: "Bạn" },
        { id: "w35", text: "khỏe" },
        { id: "w36", text: "không" },
        { id: "w37", text: "hôm" },
        { id: "w38", text: "nay" },
        { id: "w39", text: "Tôi" },
        { id: "w40", text: "rất" },
        { id: "w41", text: "tốt" },
      ],
      correctAnswers: [
        ["w37", "w38", "w34", "w35", "w36"], // Hôm nay bạn khỏe không
        ["w34", "w37", "w38", "w35", "w36"], // Bạn hôm nay khỏe không
      ],
      explanation:
        "How are you today? is 'Bạn khỏe không hôm nay' in Vietnamese",
      audioUrl: "/audio/ban-khoe-khong-hom-nay.mp3",
    },
  ],
};
